language: node_js

node_js:
  - "4.4.1"

sudo: false

branches:
  except:
    - gh-pages

script:
  - npm test

after_script:
  - if [[ `node --version` == *v4.4.1* ]]; then cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js; fi
